### PR TITLE
Fixes template element rendering problem

### PR DESCRIPTION
**Pull request by mukul0007**
This Fixes issue mentioned here -> #141 

Uses innerHTML approach for solving template element rendering in react.

### CODE REVIEW

**Review by VinayKrMittal — APPROVED** [review]
looks good to me

**Comment by sumit222ilu** [comment]
looks good to me 👍

**Review by sumit222ilu — APPROVED** [review]

**Comment by VinayKrMittal** [comment]
@Wildhoney  can we check and merge this PR to resolve template element rendering issue in react

**Comment by Wildhoney** [comment]
Thanks!

**Pull request merged**
