### PR TITLE
Adds React 18 to peer deps ranges

### PR DESCRIPTION
**Pull request by mrspence**
1. Extended `peerDependencies`  ranges to include React 18

2. Locked Travis Node JS version to 16 (LTS) so existing build/test scripts continue to work

Fix https://github.com/Wildhoney/ReactShadow/issues/137

### CODE REVIEW

**Comment by Wildhoney** [comment]
Thanks 👍 are we doing away with Husky?

**Comment by mrspence** [comment]
Ahhh! Well spotted, my mistake - brought the husky back home

**Comment by clmnin** [comment]
@Wildhoney Is the PR ready to be merged? Or should be keep using < react 18?

**Comment by lmk123** [comment]
I hope this PR will be merged soon, otherwise my project will report the following error when using npm to install dependencies:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from myapp@0.0.0
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from react-shadow@19.0.3
npm ERR! node_modules/react-shadow
npm ERR!   react-shadow@"^19.0.2" from myapp@0.0.0
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I've tried using --force or --legacy-peer-deps, but they both cause other problems, the biggest problem is that this will result in two versions of react in the project, one for 17 and the other for 18.

**Comment by mrspence** [comment]
Existing tests passing; need repo author (@Wildhoney) to confirm it is ready and approve ✅

**Comment by Wildhoney** [comment]
Thanks 👍

**Pull request merged**
