### PR TITLE
Add createProxy to support overriding target for polyfills

### PR DESCRIPTION
**Pull request by asyncLiz**
When polyfilling Proxy, there's a caveat that the target must define proxied properties in order for the polyfill to work properly.

To support this, we can export a function that creates the root Proxy and allow users to create their own Proxy instance with pre-defined properties. With a Proxy and Shadow DOM polyfill, this allows the library to be used on IE11.

```jsx
import root from 'react-shadow';

ReactDOM.render(
  <root.div>
    <h1>Doesn't work :(</h1>
  </root.div>, 
  document.querySelector('#root')
);
```
With [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill) and [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs):
```jsx
import { createProxy } from 'react-shadow';

const root = createProxy({ 
  div: undefined // pre-define all properties we want to access
});

ReactDOM.render(
  <root.div>
    <h1>Works in IE11! :)</h1>
  </root.div>, 
  document.querySelector('#root')
);
```

### CODE REVIEW

**Comment by Wildhoney** [comment]
Thanks @asyncLiz &ndash; nice addition. Released as `v17.1.2`.

**Comment by Wildhoney** [comment]
Might be nice to have a little documentation about this @asyncLiz for others facing a similar issue with `Proxy` support.

**Comment by asyncLiz** [comment]
I'll try to find some time to make another PR with some documentation updates ;)

**Comment by aliblackwell** [comment]
This looks very interesting. In my attempts to get proxy-polyfill working I edited the source of ReactShadow to include the following:
```
import ProxyPolyfillFunction from 'proxy-polyfill/src/proxy';
const ProxyPolyfill = ProxyPolyfillFunction();
```

Then, rather than:

```
export function createProxy(target = {}) {
    return new Proxy(target, {
```

I had:

```
export function createProxy(target = {}) {
    return new ProxyPolyfill(target, {
```

This stopped IE11 blowing up but wasn't working properly as I still needed to polyfill Shadow DOM itself using webcomponentsjs.

What I don't understand is how to use @asyncLiz's solution, which looks like it allows the plugin user to bring their own polyfill scripts. But given the `createProxy` function that's exported will always use a standard Proxy and the method I describe above seems to be how proxy-polyfill is meant to work, they seem incompatible with each other. 

Any insight from @asyncLiz or @Wildhoney gratefully received! I'd be happy to get it working based on comments in here and then submit a PR with clear documentation. I already forked the repo to debug this and was planning on submitting a PR with the solution.

**Comment by aliblackwell** [comment]
For the curious, I managed to stop IE11 blowing up but couldn't get the polyfill to actually do its job, a compromise I'm prepared to accept. You can see the PR for the project I'm working on here: https://github.com/DemocracyClub/WhereDoIVote-Widget/pull/266

Given I haven't actually got the polyfill working (although my approach does at least mean the react components render in IE11) I am going to leave this thread as live documentation. Perhaps @asyncLiz might still be able to shed some insight!

**Comment by asyncLiz** [comment]
@aliblackwell you'll need to polyfill the global `Proxy` variable for react-shadow to use.

```js
import { createProxy } from 'react-shadow';
import ProxyPolyfill from 'proxy-polyfill/src/proxy';

// Polyfill for react-shadow (if needed) to use `new Proxy()`
if (!window.Proxy) {
  window.Proxy = ProxyPolyfill;
}

const root = createProxy({ 
  div: undefined // pre-define all properties we want to access
});

ReactDOM.render(
  <root.div>
    <h1>Works in IE11! :)</h1>
  </root.div>, 
  document.querySelector('#root')
);
```

**Pull request merged**
